name: Test Frontend

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - '**'
      - '!main'  # Don't run on main as that will be handled by deploy workflow
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      # Cache build output to speed up subsequent builds
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('frontend/package-lock.json') }}-
            ${{ runner.os }}-nextjs-

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci
        
      - name: Debug environment
        working-directory: ./frontend
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Working directory: $(pwd)"
          ls -la
          echo "ESLint config:"
          cat .eslintrc.json

      - name: Lint
        working-directory: ./frontend
        run: npm run lint --no-fix

      - name: Build
        working-directory: ./frontend
        run: npm run build
        env:
          NODE_OPTIONS: "--verbose"
        
      # If you have tests, uncomment and adjust the following step
      # - name: Run tests
      #   working-directory: ./frontend
      #   run: npm test 